theme: jekyll-theme-modernist
show_downloads: true
resume: https://nabird27.github.io/files/Brinda_Sreenivas_Resume.pdf

title: "Brinda Sreenivas"

description: "Sophomore at University of Washington pursuing double major in Law, Societies & Justice (LSJ) and Political Science, with a minor in Data Science"
