theme: jekyll-theme-modernist
show_downloads: true
resume: https://nabird27.github.io/files/Resume-Brinda-Sreenivas.pdf

title: "Brinda Sreenivas"

description: "Junior at University of Washington pursuing<br>double major in Law, Societies & Justice (LSJ)<br>and Political Science, with a minor in Data Science"  
